version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .htaccess:/var/www/html/sf14/web/.htaccess
      - ./php.ini:/usr/local/lib/php.ini
      - ./sf14:/var/www/html/sf14/
    ports:
      - "8080:80"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: