<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2024/01/19 00:24:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sf14',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
